[
    {
        "content": "Case Studies Natural Language No Code Web Crawling Robotic Process Automation Subject Matter Expert AI Solutions Ecommerce AI Sales & Marketing Customer Support Banking Medical & Nutrition IoT & Robotics Products AI as Platform Hybrid.Chat Keyword country Site Hike The Team Our Team We Are Hiring Bl",
        "html": "<a href=\"https://smarter.codes/case-studies/\">Case Studies</a>\n<ul class=\"sub-menu\">\n<li class=\"et_pb_menu_page_id-246791 menu-item menu-item-type-post_type menu-item-object-project menu-item-246805\"><a href=\"https://smarter.codes/our-project/natural-language-understanding-of-ingredient-labels/\">Natural Language</a></li>\n<li class=\"et_pb_menu_page_id-246783 menu-item menu-item-type-post_type menu-item-object-project menu-item-246806\"><a href=\"https://smarter.codes/our-project/hybrid-chat-drag-and-drop-chatbot-builder/\">No Code</a></li>\n<li class=\"et_pb_menu_page_id-246777 menu-item menu-item-type-post_type menu-item-object-project menu-item-246807\"><a href=\"https://smarter.codes/our-project/location-extractor-crawl-millions-of-business-websites-to-find-their-office-locations/\">Web Crawling</a></li>\n<li class=\"et_pb_menu_page_id-246797 menu-item menu-item-type-post_type menu-item-object-project menu-item-246804\"><a href=\"https://smarter.codes/our-project/real-estate-rpa-assisting-users-to-fill-out-long-forms/\">Robotic Process Automation</a></li>\n<li class=\"et_pb_menu_page_id-247150 menu-item menu-item-type-custom menu-item-object-custom menu-item-247150\"><a href=\"https://smarter.codes/our-project/subject-matter-expert-ai/\">Subject Matter Expert AI</a></li>\n</ul>\n</li>\n<li class=\"et_pb_menu_page_id-29450 menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor current-menu-parent menu-item-has-children menu-item-29450\"><a href=\"#\">Solutions</a>\n<ul class=\"sub-menu\">\n<li class=\"et_pb_menu_page_id-28774 menu-item menu-item-type-post_type menu-item-object-page menu-item-28784\"><a href=\"https://smarter.codes/solutions/ecommerce-ai/\">",
        "score": 0.47,
        "url": "https://smarter.codes/solutions/iot-robotics/"
    },
    {
        "content": "Case Studies Natural Language No Code Web Crawling Robotic Process Automation Subject Matter Expert AI Solutions Ecommerce AI Sales & Marketing Customer Support Banking Medical & Nutrition IoT & Robotics Products AI as Platform Hybrid.Chat Keyword country Site Hike The Team Our Team We Are Hiring Bl",
        "score": 0.47,
        "url": "https://smarter.codes/solutions/iot-robotics/"
    },
    {
        "content": "Case Studies Natural Language No Code Web Crawling Robotic Process Automation Subject Matter Expert AI Solutions Ecommerce AI Sales & Marketing Customer Support Banking Medical & Nutrition IoT & Robotics Products AI as Platform Hybrid.Chat Keyword country Site Hike The Team Our Team We Are Hiring Bl",
        "html": "ue),n.setAttribute(t,e.nodeValue))})),e.hasAttribute(\"src\")&&this._isValidScriptType(i)?(n.addEventListener(\"load\",t),n.addEventListener(\"error\",t)):(n.text=e.text,t()),e.parentNode.replaceChild(n,e)}))}_isValidScriptType(e){return!e||\"\"===e||\"string\"==typeof e&&[\"text/javascript\",\"text/x-javascript\",\"text/ecmascript\",\"text/jscript\",\"application/javascript\",\"application/x-javascript\",\"application/ecmascript\",\"application/jscript\",\"module\"].includes(e.toLowerCase())}async _loadScriptsFromList(e){const t=e.shift();return t?(await this._transformScript(t),this._loadScriptsFromList(e)):Promise.resolve()}_preloadAllScripts(){var e=document.createDocumentFragment();[...this.delayedScripts.normal,...this.delayedScripts.defer,...this.delayedScripts.async].forEach((t=>{const n=t.getAttribute(\"src\");if(n){const t=document.createElement(\"link\");t.href=n,t.rel=\"preload\",t.as=\"script\",e.appendChild(t)}})),document.head.appendChild(e)}_delayEventListeners(){let e={};function t(t,n){!function(t){function n(n){return e[t].eventsToRewrite.indexOf(n)>=0?\"rocket-\"+n:n}e[t]||(e[t]={originalFunctions:{add:t.addEventListener,remove:t.removeEventListener},eventsToRewrite:[]},t.addEventListener=function(){arguments[0]=n(arguments[0]),e[t].originalFunctions.add.apply(t,arguments)},t.removeEventListener=function(){arguments[0]=n(arguments[0]),e[t].originalFunctions.remove.apply(t,arguments)})}(t),e[t].eventsToRewrite.push(n)}function n(e,t){let n=e[t];Object.defineProperty(e,t,{get:()=>n||function(){},set(i){e[\"rocket\"+t]=n=i}})}t(document,\"DOMContentLoaded\"),t(window,\"DOMContentLoaded\"),t(window,\"load\"),t(window,\"pageshow\"),t(document,\"readystatechange\"),n(document,\"onread",
        "score": 0.47,
        "url": "https://smarter.codes/solutions/iot-robotics/"
    },
    {
        "content": "Case Studies Natural Language No Code Web Crawling Robotic Process Automation Subject Matter Expert AI Solutions Ecommerce AI Sales & Marketing Customer Support Banking Medical & Nutrition IoT & Robotics Products AI as Platform Hybrid.Chat Keyword country Site Hike The Team Our Team We Are Hiring Bl",
        "score": 0.428,
        "url": "https://smarter.codes/solutions/customer-support/"
    },
    {
        "content": "Case Studies Natural Language No Code Web Crawling Robotic Process Automation Subject Matter Expert AI Solutions Ecommerce AI Sales & Marketing Customer Support Banking Medical & Nutrition IoT & Robotics Products AI as Platform Hybrid.Chat Keyword country Site Hike The Team Our Team We Are Hiring Bl",
        "html": "<a href=\"https://smarter.codes/case-studies/\">Case Studies</a>\n<ul class=\"sub-menu\">\n<li class=\"et_pb_menu_page_id-246791 menu-item menu-item-type-post_type menu-item-object-project menu-item-246805\"><a href=\"https://smarter.codes/our-project/natural-language-understanding-of-ingredient-labels/\">Natural Language</a></li>\n<li class=\"et_pb_menu_page_id-246783 menu-item menu-item-type-post_type menu-item-object-project menu-item-246806\"><a href=\"https://smarter.codes/our-project/hybrid-chat-drag-and-drop-chatbot-builder/\">No Code</a></li>\n<li class=\"et_pb_menu_page_id-246777 menu-item menu-item-type-post_type menu-item-object-project menu-item-246807\"><a href=\"https://smarter.codes/our-project/location-extractor-crawl-millions-of-business-websites-to-find-their-office-locations/\">Web Crawling</a></li>\n<li class=\"et_pb_menu_page_id-246797 menu-item menu-item-type-post_type menu-item-object-project menu-item-246804\"><a href=\"https://smarter.codes/our-project/real-estate-rpa-assisting-users-to-fill-out-long-forms/\">Robotic Process Automation</a></li>\n<li class=\"et_pb_menu_page_id-247150 menu-item menu-item-type-custom menu-item-object-custom menu-item-247150\"><a href=\"https://smarter.codes/our-project/subject-matter-expert-ai/\">Subject Matter Expert AI</a></li>\n</ul>\n</li>\n<li class=\"et_pb_menu_page_id-29450 menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor current-menu-parent menu-item-has-children menu-item-29450\"><a href=\"#\">Solutions</a>\n<ul class=\"sub-menu\">\n<li class=\"et_pb_menu_page_id-28774 menu-item menu-item-type-post_type menu-item-object-page menu-item-28784\"><a href=\"https://smarter.codes/solutions/ecommerce-ai/\">",
        "score": 0.428,
        "url": "https://smarter.codes/solutions/customer-support/"
    },
    {
        "content": "Case Studies Natural Language No Code Web Crawling Robotic Process Automation Subject Matter Expert AI Solutions Ecommerce AI Sales & Marketing Customer Support Banking Medical & Nutrition IoT & Robotics Products AI as Platform Hybrid.Chat Keyword country Site Hike The Team Our Team We Are Hiring Bl",
        "html": "ue),n.setAttribute(t,e.nodeValue))})),e.hasAttribute(\"src\")&&this._isValidScriptType(i)?(n.addEventListener(\"load\",t),n.addEventListener(\"error\",t)):(n.text=e.text,t()),e.parentNode.replaceChild(n,e)}))}_isValidScriptType(e){return!e||\"\"===e||\"string\"==typeof e&&[\"text/javascript\",\"text/x-javascript\",\"text/ecmascript\",\"text/jscript\",\"application/javascript\",\"application/x-javascript\",\"application/ecmascript\",\"application/jscript\",\"module\"].includes(e.toLowerCase())}async _loadScriptsFromList(e){const t=e.shift();return t?(await this._transformScript(t),this._loadScriptsFromList(e)):Promise.resolve()}_preloadAllScripts(){var e=document.createDocumentFragment();[...this.delayedScripts.normal,...this.delayedScripts.defer,...this.delayedScripts.async].forEach((t=>{const n=t.getAttribute(\"src\");if(n){const t=document.createElement(\"link\");t.href=n,t.rel=\"preload\",t.as=\"script\",e.appendChild(t)}})),document.head.appendChild(e)}_delayEventListeners(){let e={};function t(t,n){!function(t){function n(n){return e[t].eventsToRewrite.indexOf(n)>=0?\"rocket-\"+n:n}e[t]||(e[t]={originalFunctions:{add:t.addEventListener,remove:t.removeEventListener},eventsToRewrite:[]},t.addEventListener=function(){arguments[0]=n(arguments[0]),e[t].originalFunctions.add.apply(t,arguments)},t.removeEventListener=function(){arguments[0]=n(arguments[0]),e[t].originalFunctions.remove.apply(t,arguments)})}(t),e[t].eventsToRewrite.push(n)}function n(e,t){let n=e[t];Object.defineProperty(e,t,{get:()=>n||function(){},set(i){e[\"rocket\"+t]=n=i}})}t(document,\"DOMContentLoaded\"),t(window,\"DOMContentLoaded\"),t(window,\"load\"),t(window,\"pageshow\"),t(document,\"readystatechange\"),n(document,\"onread",
        "score": 0.428,
        "url": "https://smarter.codes/solutions/customer-support/"
    },
    {
        "content": "Case Studies Natural Language No Code Web Crawling Robotic Process Automation Subject Matter Expert AI Solutions Ecommerce AI Sales & Marketing Customer Support Banking Medical & Nutrition IoT & Robotics Products AI as Platform Hybrid.Chat Keyword country Site Hike The Team Our Team We Are Hiring Bl",
        "html": "<a href=\"https://smarter.codes/case-studies/\">Case Studies</a>\n<ul class=\"sub-menu\">\n<li class=\"et_pb_menu_page_id-246791 menu-item menu-item-type-post_type menu-item-object-project menu-item-246805\"><a href=\"https://smarter.codes/our-project/natural-language-understanding-of-ingredient-labels/\">Natural Language</a></li>\n<li class=\"et_pb_menu_page_id-246783 menu-item menu-item-type-post_type menu-item-object-project menu-item-246806\"><a href=\"https://smarter.codes/our-project/hybrid-chat-drag-and-drop-chatbot-builder/\">No Code</a></li>\n<li class=\"et_pb_menu_page_id-246777 menu-item menu-item-type-post_type menu-item-object-project menu-item-246807\"><a href=\"https://smarter.codes/our-project/location-extractor-crawl-millions-of-business-websites-to-find-their-office-locations/\">Web Crawling</a></li>\n<li class=\"et_pb_menu_page_id-246797 menu-item menu-item-type-post_type menu-item-object-project menu-item-246804\"><a href=\"https://smarter.codes/our-project/real-estate-rpa-assisting-users-to-fill-out-long-forms/\">Robotic Process Automation</a></li>\n<li class=\"et_pb_menu_page_id-247150 menu-item menu-item-type-custom menu-item-object-custom menu-item-247150\"><a href=\"https://smarter.codes/our-project/subject-matter-expert-ai/\">Subject Matter Expert AI</a></li>\n</ul>\n</li>\n<li class=\"et_pb_menu_page_id-29450 menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor current-menu-parent menu-item-has-children menu-item-29450\"><a href=\"#\">Solutions</a>\n<ul class=\"sub-menu\">\n<li class=\"et_pb_menu_page_id-28774 menu-item menu-item-type-post_type menu-item-object-page menu-item-28784\"><a href=\"https://smarter.codes/solutions/ecommerce-ai/\">",
        "score": 0.424,
        "url": "https://smarter.codes/solutions/sales-marketing/"
    },
    {
        "content": "Case Studies Natural Language No Code Web Crawling Robotic Process Automation Subject Matter Expert AI Solutions Ecommerce AI Sales & Marketing Customer Support Banking Medical & Nutrition IoT & Robotics Products AI as Platform Hybrid.Chat Keyword country Site Hike The Team Our Team We Are Hiring Bl",
        "html": "ue),n.setAttribute(t,e.nodeValue))})),e.hasAttribute(\"src\")&&this._isValidScriptType(i)?(n.addEventListener(\"load\",t),n.addEventListener(\"error\",t)):(n.text=e.text,t()),e.parentNode.replaceChild(n,e)}))}_isValidScriptType(e){return!e||\"\"===e||\"string\"==typeof e&&[\"text/javascript\",\"text/x-javascript\",\"text/ecmascript\",\"text/jscript\",\"application/javascript\",\"application/x-javascript\",\"application/ecmascript\",\"application/jscript\",\"module\"].includes(e.toLowerCase())}async _loadScriptsFromList(e){const t=e.shift();return t?(await this._transformScript(t),this._loadScriptsFromList(e)):Promise.resolve()}_preloadAllScripts(){var e=document.createDocumentFragment();[...this.delayedScripts.normal,...this.delayedScripts.defer,...this.delayedScripts.async].forEach((t=>{const n=t.getAttribute(\"src\");if(n){const t=document.createElement(\"link\");t.href=n,t.rel=\"preload\",t.as=\"script\",e.appendChild(t)}})),document.head.appendChild(e)}_delayEventListeners(){let e={};function t(t,n){!function(t){function n(n){return e[t].eventsToRewrite.indexOf(n)>=0?\"rocket-\"+n:n}e[t]||(e[t]={originalFunctions:{add:t.addEventListener,remove:t.removeEventListener},eventsToRewrite:[]},t.addEventListener=function(){arguments[0]=n(arguments[0]),e[t].originalFunctions.add.apply(t,arguments)},t.removeEventListener=function(){arguments[0]=n(arguments[0]),e[t].originalFunctions.remove.apply(t,arguments)})}(t),e[t].eventsToRewrite.push(n)}function n(e,t){let n=e[t];Object.defineProperty(e,t,{get:()=>n||function(){},set(i){e[\"rocket\"+t]=n=i}})}t(document,\"DOMContentLoaded\"),t(window,\"DOMContentLoaded\"),t(window,\"load\"),t(window,\"pageshow\"),t(document,\"readystatechange\"),n(document,\"onread",
        "score": 0.424,
        "url": "https://smarter.codes/solutions/sales-marketing/"
    },
    {
        "content": "Case Studies Natural Language No Code Web Crawling Robotic Process Automation Subject Matter Expert AI Solutions Ecommerce AI Sales & Marketing Customer Support Banking Medical & Nutrition IoT & Robotics Products AI as Platform Hybrid.Chat Keyword country Site Hike The Team Our Team We Are Hiring Bl",
        "score": 0.424,
        "url": "https://smarter.codes/solutions/sales-marketing/"
    }
]